context:
  name: eyed3
  version: "0.9.8"
  python_min: '3.9'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: a296ef47d8d5a5b5d7b518c113e650c7db6e47633b31a9ca81453cd48faf9803

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0
  python:
    entry_points:
      - eyed3=eyed3.main:_main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry >=0.12
  run:
    - python >=${{ python_min }}
    - filetype >=1.0.7,<2
    - deprecation >=2.1.0,<3
    - coverage >=5.3.1,<6
  run_constraints:
    - ruamel.yaml >=0.16.12,<0.17
    - pillow >=8.0.1,<10
    - pylast >=4,<5
    - requests >=2.25.0,<3

tests:
  - script:
      - eyed3 --version
  - python:
      imports:
        - eyed3
      pip_check: true
      python_version: ${{ python_min }}

about:
  homepage: https://github.com/nicfit/eyeD3
  summary: eyeD3 is a Python tool for working with audio files, specifically MP3 files containing ID3 metadata (i.e. song info).
  description: |
    eyeD3 is a Python module and command line program for processing ID3 tags. Information about mp3 files (i.e bit rate, sample frequency, play time, etc.) is also provided.
    The formats supported are ID3v1 (1.0/1.1) and ID3v2 (2.3/2.4).
  license: GPL-3.0-or-later
  license_file: LICENSE
  documentation: https://eyed3.readthedocs.io/en/latest
  repository: https://github.com/nicfit/eyeD3

extra:
  recipe-maintainers:
    - pavelzw
